### ISSUE TITLE
Transfer to BioJulia?

### ISSUE THREAD

**Issue by kescobo** [BioJulia/BioMakie.jl#550]
If you're down, please make me an admin of the repo, and I will make the transfer. Excited to have you on board! 🧬📈📊

**Comment by kescobo** [comment]
@kool7d My bad, you can't actually add an admin to a personal repo. I just invited you to BioJulia, which should make it possible for you to make the transfer. Let me know if you can't figure it out.

**Comment by kool7d** [comment]
@kescobo I transferred it to BioJulia. I was looking for the settings though and it appears that I don't have access anymore.

**Comment by kescobo** [comment]
This should be all set now, right @kool7d ?

**Comment by kool7d** [comment]
Yes, thank you @kescobo
